### ISSUE TITLE
Produkt Bilder

### ISSUE THREAD

**Issue by 2e12** [2e12/426-scrum-project#33]
** Beschreibung **
Einem Produkt können Bilder hinterlegt werden

** Akzeptanzkriterien **
- Bilder können einem Produkt hinzugefügt werden
- Bilder werden auf dem FileSystem der jeweiligen Umgebung gespeichert
- In der Datenbank wird ein Link auf die Bilddatei hinterlegt
- Bilder werden ins Format jpeg und auf eine kleinere grösse skaliert
- Die Links zu den Bilder werden von der API auf dem jweeiligen Produkt Endpoint zurückgegeben

**Comment by 2e12** [comment]
https://github.com/encode/starlette/issues/1059

**Comment by Ha21iko** [comment]
Aufgewendete Zeit: 3.5 Std.
